# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_text', models.TextField()),
                ('impact_text', models.TextField()),
                ('add_date', models.DateTimeField(verbose_name='date added')),
                ('due_date', models.DateTimeField(verbose_name='complete by')),
                ('priority', models.FloatField()),
            ],
        ),
    ]
