# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(default='', max_length=200)),
                ('desc_text', models.TextField()),
                ('impact_text', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('due_date', models.DateTimeField()),
                ('priority', models.FloatField(default='-1')),
                ('complete', models.BooleanField(default=False)),
            ],
        ),
    ]
