# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 22:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 21, 22, 57, 41, 368729, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='priority',
            field=models.FloatField(),
        ),
    ]
