# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='title_text',
            field=models.CharField(default='', max_length=200),
        ),
    ]
