# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20170621_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='complete',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='title_text',
            field=models.CharField(max_length=200),
        ),
    ]
