# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-25 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20170625_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='complete',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='priority',
            field=models.FloatField(),
        ),
    ]
