# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20170625_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='username',
            field=models.CharField(default='admin', max_length=200),
            preserve_default=False,
        ),
    ]
